# Generated by Django 5.2 on 2025-04-27 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomm', models.CharField(max_length=50)),
                ('niveaum', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomv', models.CharField(max_length=50)),
                ('histoire', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='personnels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=55)),
                ('daten', models.CharField(max_length=50)),
                ('niveaup', models.CharField(max_length=80)),
                ('famille', models.CharField(max_length=80)),
                ('metier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emploi_village.metier')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='emploi_village.ville')),
            ],
        ),
    ]
