# Generated by Django 5.2 on 2025-05-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_village', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metier',
            name='niveaum',
            field=models.CharField(max_length=50, verbose_name='Niveau requis'),
        ),
        migrations.AlterField(
            model_name='metier',
            name='nomm',
            field=models.CharField(max_length=50, verbose_name='Nom du métier'),
        ),
        migrations.AlterField(
            model_name='personnels',
            name='daten',
            field=models.CharField(max_length=50, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='personnels',
            name='famille',
            field=models.CharField(max_length=80, verbose_name='Situation familiale'),
        ),
        migrations.AlterField(
            model_name='personnels',
            name='niveaup',
            field=models.CharField(max_length=80, verbose_name="Niveau d'étude"),
        ),
        migrations.AlterField(
            model_name='personnels',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='personnels',
            name='tel',
            field=models.CharField(max_length=55, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='histoire',
            field=models.CharField(max_length=255, verbose_name='Histoire'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='nomv',
            field=models.CharField(max_length=50, verbose_name='Nom de la ville'),
        ),
    ]
