# Generated by Django 5.2 on 2025-05-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_village', '0002_alter_metier_niveaum_alter_metier_nomm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='histoire',
            field=models.CharField(max_length=1000, verbose_name='Histoire'),
        ),
    ]
