# Generated by Django 5.2 on 2025-05-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_village', '0003_alter_ville_histoire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnels',
            name='metier',
        ),
        migrations.AddField(
            model_name='personnels',
            name='metier',
            field=models.ManyToManyField(to='emploi_village.metier'),
        ),
    ]
