# Generated by Django 5.2 on 2025-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_village', '0004_remove_personnels_metier_personnels_metier'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnels',
            name='gmail',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Gmail'),
        ),
    ]
