# Generated by Django 5.2 on 2025-05-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_village', '0005_personnels_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnels',
            name='Residence',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de Residence'),
        ),
    ]
