# Generated by Django 5.2.1 on 2025-05-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_village', '0006_personnels_residence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnels',
            name='Residence',
        ),
        migrations.AddField(
            model_name='personnels',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='personnels',
            name='daten',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personnels',
            name='famille',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personnels',
            name='gmail',
            field=models.EmailField(default='cedricnyacke@gmail.com', max_length=254),
        ),
        migrations.RemoveField(
            model_name='personnels',
            name='metier',
        ),
        migrations.AlterField(
            model_name='personnels',
            name='niveaup',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personnels',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personnels',
            name='tel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personnels',
            name='ville',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='personnels',
            name='residence',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='personnels',
            name='metier',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
