# Generated by Django 5.2.1 on 2025-05-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_village', '0007_remove_personnels_residence_personnels_cv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnels',
            name='metier',
        ),
        migrations.AlterField(
            model_name='personnels',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi_village.ville'),
        ),
        migrations.AddField(
            model_name='personnels',
            name='metier',
            field=models.ManyToManyField(to='emploi_village.metier'),
        ),
    ]
