# Generated by Django 5.2 on 2025-06-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_village', '0008_remove_personnels_metier_alter_personnels_ville_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
