# Generated by Django 5.2.1 on 2026-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_village', '0009_actualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actualites/images/'),
        ),
        migrations.AddField(
            model_name='actualite',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='actualites/videos/'),
        ),
    ]
