"""
Django settings for village project.

Generated by 'django-admin startproject' using Django 5.2.
"""

import os
from pathlib import Path


# ============================================================
# BASE DIR
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

# En production, il est préférable de mettre SECRET_KEY
# dans une variable d'environnement.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-5mg54326l0_glwjlm70$0y+i2*=v%os#^_9e@a7$47+_knqisi"
)

# Pour PythonAnywhere
DEBUG = False


# ============================================================
# ALLOWED HOSTS
# ============================================================

# Nous ajouterons ton véritable domaine PythonAnywhere
# lorsqu'il sera connu.
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    "dal",
    "dal_select2",

    "emploi_village",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise pour les fichiers statiques
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "village.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "village.wsgi.application"


# ============================================================
# DATABASE
# ============================================================

# Pour PythonAnywhere, nous utilisons SQLite.
#
# La base sera créée dans :
#
# BASE_DIR / "db.sqlite3"
#
# Il n'y a donc plus besoin de :
# - MySQL
# - localhost:3306
# - root
# - mot de passe MySQL
# - PyMySQL


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "fr-FR"

TIME_ZONE = "Africa/Douala"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


# WhiteNoise
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# CSRF
# ============================================================

# Pour le moment, nous conservons uniquement les adresses
# locales.
#
# Le domaine PythonAnywhere sera ajouté dès que nous
# connaîtrons ton nom d'utilisateur PythonAnywhere.

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================
# EMAIL - GMAIL
# ============================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = "smtp.gmail.com"

EMAIL_PORT = 587

EMAIL_USE_TLS = True

# Les informations Gmail doivent être placées dans
# les variables d'environnement.
#
# EMAIL_HOST_USER
# EMAIL_HOST_PASSWORD

EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER",
    ""
)

EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD",
    ""  # À renseigner sur PythonAnywhere
)


# ============================================================
# HTTPS / SECURITY
# ============================================================

# Nous l'activerons lorsque le site PythonAnywhere sera
# configuré en HTTPS.

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)

SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SECURE = True


# ============================================================
# FILE UPLOAD
# ============================================================

# Limites raisonnables pour les fichiers envoyés par
# l'application.

DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# ============================================================
# AUTHENTIFICATION
# ============================================================

LOGIN_URL = "/connexion/"

LOGIN_REDIRECT_URL = "/"

LOGOUT_REDIRECT_URL = "/"